### ISSUE TITLE
OIDC throws exception: Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vincentbitter** [Place1/wg-access-server#19]
Hi, just updated to the latest version of wg-access-server, but unfortunately OIDC still doesn't work for me. I am trying to connect to keycloak with the following config.yaml:

```
auth:
  oidc:
    name: "xxx"
    issuer: "https://login.xxx.nl/auth/realms/master"
    clientID: "secure"
    clientSecret: "xxxxxxx-xxx-xxxx-xxxx-xxxxxxxx"
    redirectURL: "https://vpn.xxx.nl"

```

Version 0.0.9:
1. Shows wg-access-server screen with 'Sign In: [OIDC]'
2. Click on OIDC => Redirects to Keycloak and allows to login
3. Redirects to wg-access-server with 'Sign In: [OIDC]'
4. Click on OIDC => Redirects to Keycloak and immideately goes back to step 3.

Version 0.1.0:
1. Shows wg-access-server screen with 'Sign In: [OIDC]'
2. Click on OIDC => Redirects to Keycloak and allows to login
3. Throws this exception:
```
http: panic serving 172.18.0.7:40598: runtime error: invalid memory address or nil pointer dereference
goroutine 186 [running]:
net/http.(*conn).serve.func1(0xc00013b0e0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xbb86c0, 0x12e2730)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
main.main.func2(0x0, 0xc000362fa0, 0xc00051e800)
	/code/main.go:131 +0x2a
github.com/place1/wg-access-server/pkg/authnz.(*AuthMiddleware).Wrap.func4(0xdcd9a0, 0xc0003467e0, 0xc00051e800)
	/code/pkg/authnz/router.go:69 +0x3b2
net/http.HandlerFunc.ServeHTTP(0xc00053e810, 0xdcd9a0, 0xc0003467e0, 0xc00051e800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001a0780, 0xdcd9a0, 0xc0003467e0, 0xc00051e600)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001a0000, 0xdcd9a0, 0xc0003467e0, 0xc00051e400)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc0004680e0, 0xdcd9a0, 0xc0003467e0, 0xc00051e400)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00013b0e0, 0xdcf720, 0xc0003ea300)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
```

**Comment by Place1** [comment]
I've reproduced this. This is happening because the redirect URL is "/".

The oauth redirect URL needs to be something unique and not used by the rest of the application; in this case when "/" is used the oauth callback hits the home page and so wg-access-server never gets the user's userinfo. The panic is from a bit of code expecting this info (the subject) and not finding it.

Give it another try with `redirectURL: "https://vpn.xxx.nl/auth/callback"`. Remember to update the callback URL on the Keycloak side as well.

I think I'll push a patch to throw a nice "config error" type message when the redirect url conflicts like this.

**Comment by vincentbitter** [comment]
Awesome, it works!

**Comment by Place1** [comment]
great!
