### ISSUE TITLE
Why is MySQL marked as non-ha?

### ISSUE THREAD

**Issue by hongkongkiwi** [Place1/wg-access-server#80]
I notice that mysql is marked as non-HA compatible, I was wondering why that is?

I would have thought that since every instant of the running server can access the MySQL server then it should be HA?

I would like to spin up some additional nodes but am planning to use the MySQL backend.

**Comment by Place1** [comment]
I've just merged the first stab at HA support in #89 

The reason i've only marked HA as supported with postgres is because the HA implementation is powered by device add/remove events being emitted from the storage backend.

Postgres supports events with the LISTEN/NOTIFY feature.

I'm not as familiar with mysql but if it can support add/remove events in a similar way then we can add HA support for mysql as well. Perhaps the mysql replication logs (I think it's referred to as bin logs?) may support this use-case.

Alternatively it would be possible to support HA with mysql and other backends using a polling-based solution.

If you're interested in developing this then i can point you in the right direction. You'll need to implement a [Watcher](https://github.com/Place1/wg-access-server/blob/master/internal/storage/contracts.go#L22) and then get the sql backend to use your watcher when `mysql://` is being used [here](https://github.com/Place1/wg-access-server/blob/master/internal/storage/sql.go#L116).
